on:
  workflow_dispatch:
  push:
    branches: main

name: Deploy Test without Quarto

jobs:

  deploy-test:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::remotes
            any::visNetwork
            any::bsicons
            any::plotly
            github::ropensci-review-tools/pkgmatch@main
            github::ropensci-review-tools/orgmetrics@main
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Orgmetrics deploy
        run: Rscript -e "options('rlang_message_verbosity'='verbose'); orgmetrics::orgmetrics_deploy_r_univ(url='https://github.com/${{ github.repository }}')"
        env:
          R_CRAN_WEB: "https://cloud.r-project.org"
          GITHUB_TOKEN: ${{ github.token }}
