on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: 0 0 * * *

name: Quarto Publish

jobs:

  quarto-build-deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'

      - name: Install sysdeps
        run: |
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libcairo2-dev

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          r-version: 'renv'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}

      - name: Install orgmetrics package
        run: Rscript -e "remotes::install_github('ropensci-review-toools/orgmetrics')"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}

      - name: Orgmetrics deploy
        run: Rscript -e "orgmetrics::orgmetrics_deploy_r_univ(url=${{ github.repository }})"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: quarto
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}
